# Generated by Django 5.1.4 on 2025-01-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='station_login',
        ),
        migrations.AlterField(
            model_name='police_station',
            name='addressline2',
            field=models.CharField(max_length=100),
        ),
    ]
