# Generated by Django 5.1.4 on 2025-01-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_rename_login_station_login_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='station_login',
            new_name='login',
        ),
    ]
