# Generated by Django 5.1.4 on 2025-01-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_rename_station_login_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='login',
            name='usertype',
            field=models.IntegerField(null=True),
        ),
    ]
