# Generated by Django 5.1.4 on 2025-01-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_user_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='criminals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='criminalface/')),
                ('criminal_name', models.CharField(max_length=100)),
                ('crime_details', models.CharField(max_length=500)),
                ('criminal_age', models.IntegerField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='staff_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_address', models.CharField(max_length=100)),
                ('staff_district', models.CharField(max_length=100)),
                ('staff_city', models.CharField(max_length=100)),
                ('staff_contact', models.CharField(max_length=100)),
                ('staff_dob', models.CharField(max_length=100)),
                ('staff_designation', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('staff_login_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.login')),
            ],
        ),
    ]
