# Generated by Django 5.1.4 on 2025-02-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_criminals_staff_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminals',
            name='login_staffid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.staff_reg'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='criminal_age',
            field=models.IntegerField(),
        ),
    ]
