# Generated by Django 5.1.4 on 2025-02-08 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_criminals_login_staffid_alter_criminals_criminal_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_reg',
            name='staff_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.police_station'),
        ),
    ]
