# Generated by Django 5.1.4 on 2025-02-08 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_staff_reg_staff_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=100)),
                ('current_date', models.CharField(max_length=100)),
                ('staff_login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.login')),
            ],
        ),
    ]
