# Generated by Django 5.1.4 on 2025-02-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='current_date',
            field=models.DateField(),
        ),
    ]
