# Generated by Django 5.1.4 on 2025-02-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_alter_duty_current_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='duty',
            new_name='duties',
        ),
    ]
