# Generated by Django 5.1.4 on 2025-02-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_rename_duty_duties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duties',
            name='current_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
