# Generated by Django 5.1.4 on 2025-02-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0012_alter_duties_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_reg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
