# Generated by Django 5.1.4 on 2025-02-08 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0013_alter_staff_reg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='duties',
            name='station_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projectapp.login'),
        ),
        migrations.AlterField(
            model_name='duties',
            name='staff_login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.staff_reg'),
        ),
    ]
