# Generated by Django 5.1.4 on 2025-02-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_duties_station_id_alter_duties_staff_login_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duties',
            old_name='station_id',
            new_name='login_id',
        ),
    ]
