# Generated by Django 5.1.4 on 2025-02-10 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_rename_station_id_duties_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duties',
            name='login_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='duties_as_login', to='projectapp.login'),
        ),
        migrations.AlterField(
            model_name='duties',
            name='staff_login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties_as_staff', to='projectapp.login'),
        ),
    ]
