# Generated by Django 5.1.4 on 2025-02-11 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0016_alter_duties_login_id_alter_duties_staff_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=25)),
                ('case_details', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=15)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('station_login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_as_station', to='projectapp.login')),
                ('user_login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_as_user', to='projectapp.login')),
            ],
        ),
    ]
