# Generated by Django 5.1.4 on 2025-02-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0017_petition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='station_login',
            new_name='login_id',
        ),
        migrations.RenameField(
            model_name='petition',
            old_name='user_login',
            new_name='login_userid',
        ),
        migrations.AlterField(
            model_name='police_station',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
