# Generated by Django 5.1.4 on 2025-02-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0018_rename_station_login_petition_login_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='login_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='petition_as_station', to='projectapp.login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petition',
            name='login_userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='petition_as_user', to='projectapp.login'),
            preserve_default=False,
        ),
    ]
