# Generated by Django 5.1.4 on 2025-02-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0019_alter_petition_login_id_alter_petition_login_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='login_id',
            field=models.ForeignKey(blank=True, db_column='station_login_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_as_station', to='projectapp.login'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='login_userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_as_user', to='projectapp.login'),
        ),
    ]
