# Generated by Django 5.1.4 on 2025-02-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0020_alter_petition_login_id_alter_petition_login_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='login_userid',
        ),
    ]
