# Generated by Django 5.1.4 on 2025-02-11 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0021_remove_petition_login_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='login_userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_as_user', to='projectapp.login'),
        ),
    ]
