# Generated by Django 5.1.4 on 2025-02-15 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0022_petition_login_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_reg',
            name='staff_login_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_login_set', to='projectapp.login'),
        ),
        migrations.AlterField(
            model_name='staff_reg',
            name='staff_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_station_set', to='projectapp.login'),
        ),
    ]
