# Generated by Django 5.1.4 on 2025-02-15 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0025_alter_staff_reg_staff_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police_station',
            name='login_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectapp.login'),
        ),
    ]
