# Generated by Django 5.1.4 on 2025-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0027_alter_petition_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='case',
            field=models.CharField(max_length=100),
        ),
    ]
