# Generated by Django 5.1.4 on 2025-02-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0028_alter_petition_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_no', models.IntegerField(max_length=10)),
                ('date_time', models.CharField(max_length=20)),
                ('acts', models.CharField(max_length=50)),
                ('sections', models.CharField(max_length=40)),
                ('occurrence_time', models.CharField(max_length=40)),
                ('recieved_time', models.CharField(max_length=10)),
                ('details_suspect', models.CharField(max_length=100)),
                ('properties_involved', models.CharField(max_length=100)),
                ('total_value_property', models.CharField(max_length=100)),
                ('content_fir', models.CharField(max_length=200)),
            ],
        ),
    ]
