# Generated by Django 5.1.4 on 2025-02-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0029_fir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fir',
        ),
    ]
