# Generated by Django 5.1.4 on 2025-02-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0030_delete_fir'),
    ]

    operations = [
        migrations.CreateModel(
            name='fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_no', models.IntegerField(max_length=10)),
                ('date_time', models.CharField(max_length=20)),
                ('acts', models.CharField(max_length=50)),
                ('sections', models.CharField(max_length=40)),
                ('occurrence_time', models.CharField(max_length=40)),
                ('recieved_time', models.CharField(max_length=10)),
                ('details_suspect', models.CharField(max_length=100)),
                ('properties_involved', models.CharField(max_length=100)),
                ('total_value_property', models.CharField(max_length=100)),
                ('content_fir', models.CharField(max_length=200)),
                ('staff_loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fir_as_staff', to='projectapp.login')),
            ],
        ),
    ]
