# Generated by Django 5.1.4 on 2025-02-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0031_fir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='fir_no',
            field=models.IntegerField(),
        ),
    ]
