# Generated by Django 5.1.4 on 2025-02-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0034_petition_fir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
