# Generated by Django 5.1.4 on 2025-02-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0035_alter_petition_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='public_petition_id',
        ),
        migrations.DeleteModel(
            name='petition',
        ),
    ]
