# Generated by Django 5.1.4 on 2025-02-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0036_remove_fir_public_petition_id_delete_petition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fir',
        ),
    ]
