# Generated by Django 5.1.4 on 2025-02-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0038_petition_fir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fir',
        ),
    ]
