# Generated by Django 5.1.4 on 2025-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0040_fir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
