# Generated by Django 5.1.4 on 2025-02-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0041_alter_fir_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fir',
        ),
    ]
