# Generated by Django 5.1.4 on 2025-02-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0042_delete_fir'),
    ]

    operations = [
        migrations.CreateModel(
            name='fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('pstation', models.CharField(max_length=50)),
                ('fir_no', models.IntegerField()),
                ('year', models.DateField(max_length=40)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('acts', models.CharField(max_length=50)),
                ('sections', models.CharField(max_length=40)),
                ('occurrence_day', models.CharField(max_length=40)),
                ('occurrence_date', models.DateField(max_length=40)),
                ('occurrence_time', models.TimeField(max_length=40)),
                ('occurrence_place', models.CharField(max_length=40)),
                ('recieved_time', models.TimeField()),
                ('details_case', models.CharField(max_length=200)),
                ('details_suspect', models.CharField(max_length=100)),
                ('properties_involved', models.CharField(max_length=100)),
                ('total_value_property', models.CharField(max_length=100)),
                ('content_fir', models.CharField(max_length=200)),
                ('public_petition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_as_id', to='projectapp.petition')),
                ('staff_loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fir_as_staff', to='projectapp.login')),
            ],
        ),
    ]
