# Generated by Django 5.1.4 on 2025-02-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0043_fir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='login_userid',
        ),
        migrations.DeleteModel(
            name='fir',
        ),
        migrations.DeleteModel(
            name='petition',
        ),
    ]
