# Generated by Django 5.1.4 on 2025-02-16 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0044_remove_petition_login_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=100)),
                ('case_details', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('recieved_time1', models.TimeField(auto_now_add=True)),
                ('place', models.CharField(max_length=100)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('suspect', models.CharField(max_length=150)),
                ('login_id', models.ForeignKey(blank=True, db_column='station_login_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_as_station', to='projectapp.login')),
                ('login_userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_as_user', to='projectapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('pstation', models.CharField(max_length=50)),
                ('fir_no', models.IntegerField()),
                ('year', models.DateField(max_length=40)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('acts', models.CharField(max_length=50)),
                ('sections', models.CharField(max_length=40)),
                ('occurrence_day', models.CharField(max_length=40)),
                ('occurrence_date', models.DateField(max_length=40)),
                ('occurrence_time', models.TimeField(max_length=40)),
                ('occurrence_place', models.CharField(max_length=40)),
                ('recieved_time', models.TimeField()),
                ('details_case', models.CharField(max_length=200)),
                ('details_suspect', models.CharField(max_length=100)),
                ('properties_involved', models.CharField(max_length=100)),
                ('total_value_property', models.CharField(max_length=100)),
                ('content_fir', models.CharField(max_length=200)),
                ('staff_loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fir_as_staff', to='projectapp.login')),
                ('public_petition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_as_id', to='projectapp.petition')),
            ],
        ),
    ]
