# Generated by Django 5.1.4 on 2025-02-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0045_petition_fir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='content_fir',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fir',
            name='details_case',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fir',
            name='details_suspect',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fir',
            name='occurrence_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fir',
            name='occurrence_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='fir',
            name='properties_involved',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fir',
            name='year',
            field=models.DateField(),
        ),
    ]
