# Generated by Django 5.1.4 on 2025-02-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0047_alter_fir_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='details_case',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='occurrence_date',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='occurrence_day',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='occurrence_place',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='occurrence_time',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='recieved_time',
        ),
    ]
