# Generated by Django 5.1.4 on 2025-02-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0048_remove_fir_details_case_remove_fir_occurrence_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='details_suspect',
        ),
    ]
