# Generated by Django 5.1.4 on 2025-02-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0049_remove_fir_details_suspect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='login_userid',
        ),
        migrations.DeleteModel(
            name='fir',
        ),
        migrations.DeleteModel(
            name='petition',
        ),
    ]
