# Generated by Django 5.1.4 on 2025-02-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0051_petition_fir'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='case_status',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
