# Generated by Django 5.1.4 on 2025-02-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0052_petition_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='case_status',
            field=models.CharField(max_length=200),
        ),
    ]
