# Generated by Django 5.1.4 on 2025-02-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0054_alter_petition_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
