# Generated by Django 5.1.4 on 2025-02-18 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0055_alter_petition_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=400)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('user_logid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.login')),
            ],
        ),
    ]
