# Generated by Django 5.1.4 on 2025-02-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0056_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaint',
            field=models.TextField(),
        ),
    ]
