# Generated by Django 5.1.4 on 2025-02-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0057_alter_complaints_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='reply',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
