# Generated by Django 5.1.4 on 2025-02-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0058_complaints_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry', models.CharField(max_length=400, null=True)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('staff_reply', models.CharField(max_length=400, null=True)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_as_id', to='projectapp.login')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_as_id', to='projectapp.login')),
            ],
        ),
    ]
