# Generated by Django 5.1.4 on 2025-02-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0059_enquiries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='enquiry',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enquiries',
            name='staff_reply',
            field=models.TextField(),
        ),
    ]
