# Generated by Django 5.1.4 on 2025-02-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0060_alter_enquiries_enquiry_alter_enquiries_staff_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiries',
            old_name='station_id',
            new_name='login_id',
        ),
    ]
