# Generated by Django 5.1.4 on 2025-03-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0061_rename_station_id_enquiries_login_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiries',
            old_name='login_id',
            new_name='station_id',
        ),
    ]
