# Generated by Django 5.1.4 on 2025-03-01 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0062_rename_login_id_enquiries_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='login_userid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_as_loginid', to='projectapp.login'),
        ),
    ]
