# Generated by Django 5.1.4 on 2025-03-01 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0063_alter_user_reg_login_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police_station',
            name='login_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='station_as_loginid', to='projectapp.login'),
        ),
    ]
