# Generated by Django 5.1.4 on 2025-03-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0066_alter_staff_reg_staff_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_reg',
            name='staff_designation',
            field=models.CharField(choices=[('Constable', 'Constable'), ('Head Constable', 'Head Constable'), ('SHO', 'SHO'), ('ASI', 'ASI'), ('Sub Inspector', 'Sub Inspector'), ('Inspector', 'Inspector'), ('DYSP', 'DYSP')], max_length=30),
        ),
    ]
