# Generated by Django 5.1.4 on 2025-04-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0068_alter_staff_reg_staff_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(auto_now_add=True)),
                ('petition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpetition_as_id', to='projectapp.petition')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.staff_reg')),
            ],
        ),
    ]
